### ISSUE TITLE
Holonomic pathPlanning

### ISSUE THREAD

**Issue by formica-multiuso** [aidyk/SGMP#1]
Hi, and thanks for sharing your code!
I'm trying to use your plugin with V-REP 3.1.3 (rev 2b) 64bit on Ubuntu Linux.
After having solved some compile error (some include missing) I succesfully compiled the library, and loaded it.
Testing it with the provided V-REP official examples, it seems that the non-holonomic path planning works properly. The holonomic path planning does not work at all (I tried RRT), it doesn't return any solution.
Using RRTstar (or other non-standard RRT's versions) the simulator crash completely.

Any idea?
Can you provide me infos about your working compiler?

Regards
Roberto

**Comment by aidyk** [comment]
Sorry for late reply, I also recognize that the initial version is unstable with lots of issues and I couldn't afford to deal with it for past few months. I'll be figuring it out this week, and thank you for your interest-!

Regards,
A.I Dyk

**Comment by formica-multiuso** [comment]
Thanks for the reply.
I managed to run only BiRRT.
RRT, RRT\* and RRG doesn't work at all.

A side question: which is the exact syntax of setting.cfg to work with RRT?
I'm using an empty file with just one line:

RRT goalBias 0.5

Is it correct?

Thanks in advance
Roberto

**Comment by aidyk** [comment]
The format is currently, one parameter per line as below
Planner Type(e.g., RRT, RRT*, BiRRT, RRG)
Parameter1 value1
Parameter2 value2
...
But the parameters aren't fully functionable yet now, I'll update them ASAP in near furture.
Thank you for your interest again-

Regards,
A.I Dyk
